sudo: required
language: python
# 2.7 for CentOS7, 3.5 for OSX
python:
- '2.7'
- '3.5'
# Secure Environment Variables
env:
  secure: b1M8f4Zc2iKTTmJOKah0MQPv9Qiv/p4ExOkyzoEW04sX7uiEQ/d5sIJBCdDAFA3NlrNTAiOFf5jFj6UEHEqr8y0XzRYgQdYfi1Sy7rW0I5p8MIqbOoJExC4epEQAaWAQ0noXIR/Hgb7jr33VA5VFYiD5mkR2zCmtI9mvF9pdMpw=
# Setup the env (test dependencies)
before_install:
- ifconfig -a
- sudo /sbin/modprobe tun
- sudo apt-get update -qq
- sudo apt-get install -qq dynamips netcat
# install the crassh & dep
install:
- pip install .
- pip install paramiko
# Get ready for the test script
before_script:
- wget -q $IOS_URL
- ls -l
- sudo dynamips -i 1 -s 0:0:tap:tap0 -P 3725 -T 2001 --idle-pc=0x607081e0 -C tests/r1.txt c3725-advsecurityk9-mz.124-25c.bin &
- r1pid=$!
- echo $r1pid
- sudo dynamips -i 2 -s 0:0:tap:tap1 -P 3725 -T 2002 --idle-pc=0x607081e0 -C tests/r2.txt c3725-advsecurityk9-mz.124-25c.bin &
- r2pid=$!
- echo $r2pid
- sudo ifconfig tap0 inet 1.1.1.1 netmask 255.255.255.252
- sudo ifconfig tap1 inet 1.1.1.5 netmask 255.255.255.252
- ifconfig -a
# Sleep until the interfaces are up
- count=0;until ping -c 4 1.1.1.2 || (( count++ >= 15 )); do echo " Ping [$count] sleeping for 2 seconds ";sleep 2; done
- count=0;until ping -c 4 1.1.1.6 || (( count++ >= 15 )); do echo " Ping [$count] sleeping for 2 seconds ";sleep 2; done
# Sleep until SSH is up
- count=0;until nc -z 1.1.1.2 22 || (( count++ >= 30 )); do echo " SSH [$count] sleeping for 2 seconds ";sleep 2; done
- count=0;until nc -z 1.1.1.6 22 || (( count++ >= 30 )); do echo " SSH [$count] sleeping for 2 seconds ";sleep 2; done
# command to run tests (--cisco enables the dynamips tests)
script:
- py.test --cisco
- bin/crassh -h
# Shutdown Dynamips
- sudo kill -SIGTERM $r1pid
- sudo kill -SIGTERM $r2pid
branches:
  except:
    - docs
